apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: coldsense
  labels:
    app: coldsense-backend
spec:
  type: LoadBalancer
  selector:
    app: coldsense-backend
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
  sessionAffinity: None
  externalTrafficPolicy: Cluster
